Repository honeycombio/libhoney-js, pull requests merged in 2021-08, with the labels that each got.

#168 Prepare v2.3.1 release
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: version: bump patch, type: maintenance

#170 fix: remove yarn from engines
  package.json
Labels: type: bug, version: bump patch

#173 Add OSS lifecycle badge
  OSSMETADATA
  README.md
Labels: version: no bump
