Repository honeycombio/libhoney-js, pull requests merged in 2022-04, with the labels that each got.

#252 maint: remove unused script
  package.json
Labels: type: maintenance, version: no bump, merge at will

#253 Handle `null` transmission in `flush`
  package.json
  setupTests.js
  src/__tests__/libhoney_test.js
  src/libhoney.js
Labels: type: bug, version: bump patch

#255 Update tests to properly terminate
  src/__tests__/transmission_test.js
Labels: type: bug, type: maintenance
