Repository honeycombio/libhoney-js, pull requests merged in 2023-08, with the labels that each got.

#389 fix: replace superagent-proxy with direct use of proxy-agent
  package-lock.json
  package.json
  rollup.browser.config.js
  rollup.config.js
  src/transmission.js
Labels: type: security

#390 maint: extra test to check for http info from proxy
  docker-compose.yml
  examples/express/app.js
  examples/express/express-honey.js
  src/__tests__/transmission_test.js
Labels: type: maintenance, no-changelog, version: no-bump

#391 rel: prep release v4.1.0
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: no-changelog
